#!/usr/bin/env sh

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120             \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff7fc06e     \
    normal_window_border_color   0x88555555     \
    window_border                on             \
    window_border_width          4              \
    window_border_radius         8              \
    window_border_blur           off            \
    window_border_hidpi          on             \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  8              \
    bottom_padding               8              \
    left_padding                 8              \
    right_padding                8              \
    window_gap                   6              \
    layout                       bsp            \
    mouse_modifier               alt            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m rule --add app="(システム設定|System Settings)" manage=off
yabai -m rule --add app="(システム情報|System Information)" manage=off
yabai -m rule --add app="インストーラ" manage=off
yabai -m rule --add app="1Password" manage=off

echo "yabai configuration loaded.."
