- block:
    - name: Run the equivalent of "apt-get update" as a separate step
      become: true
      apt:
        update_cache: yes

    - name: Install tools using apt
      become: true
      apt:
        pkg:
          - fzf
          - gufw
          - htop
          - jq
          - peco
          - tig
          - tmux
          - xclip
        state: present
        update_cache: yes

    - name: Install tools
      become: true
      shell: make install_tools

    - name: Install with cargo
      shell: cargo install --locked {{ item }}
      environment:
        PATH: "{{ansible_env.PATH}}:$HOME/.cargo/env"
      loop:
        - bat
        - cargo-update
        - exa
        - killport

    - name: Install rtx
      environment:
        PATH: "{{ansible_env.PATH}}:$HOME/.cargo/env"
      command: make setup/rtx

    - name: Install alacritty dependencies
      become: true
      apt:
        pkg:
          - cmake
          - pkg-config
          - libfreetype6-dev
          - libfontconfig1-dev
          - libxcb-xfixes0-dev
          - libxkbcommon-dev
          - python3
        state: present
        update_cache: yes

    - name: Build alacritty
      become: true
      environment:
        PATH: "{{ansible_env.PATH}}:$HOME/.cargo/env"
      command: make setup/alacritty

    - name: Install neovim dependencies
      become: true
      apt:
        pkg:
          - ninja-build
          - gettext
          - libtool
          - libtool-bin
          - autoconf
          - automake
          - cmake
          - g++
          - pkg-config
          - unzip
          - curl
        state: present
        update_cache: yes

    - name: Build neovim
      become: true
      shell: make setup/nvim

  when: ansible_os_family == "Debian"
