- block:
    - name: Run the equivalent of "apt-get update" as a separate step
      become: true
      apt:
        update_cache: yes

    - name: Install tools using apt
      become: true
      apt:
        pkg:
          - bat
          - exa
          - fish
          - fzf
          - gufw
          - htop
          - hub
          - jq
          - peco
          - tig
          - tmux
          - xclip
        state: present
        update_cache: yes

    - name: Install alacritty dependencies
      become: true
      apt:
        pkg:
          - cmake
          - pkg-config
          - libfreetype6-dev
          - libfontconfig1-dev
          - libxcb-xfixes0-dev
          - libxkbcommon-dev
          - python3
        state: present
        update_cache: yes

    - name: Install rust
      become: true
      shell: make setup/rust

    - name: Build alacritty
      become: true
      shell: source "$HOME/.cargo/env" && make setup/alacritty
      args:
        executable: /bin/bash

    - name: Install neovim dependencies
      become: true
      apt:
        pkg:
          - ninja-build
          - gettext
          - libtool
          - libtool-bin
          - autoconf
          - automake
          - cmake
          - g++
          - pkg-config
          - unzip
          - curl
        state: present
        update_cache: yes

    - name: Build neovim
      become: true
      shell: make setup/nvim

  when: ansible_os_family == "Debian"
