- block:
    - name: Run the equivalent of "apt-get update" as a separate step
      become: true
      apt:
        update_cache: yes

    - name: Install tools using apt
      become: true
      apt:
        pkg:
          - build-essential
          - fzf
          - gufw
          - htop
          - jq
          - libbz2-dev
          - libffi-dev
          - libncurses5-dev
          - libreadline-dev
          - libsqlite3-dev
          - libssl-dev
          - peco
          - pkg-config
          - tig
          - tmux
          - unzip
          - xclip
          - zip
          - zlib1g
          - zlib1g-dev
        state: present
        update_cache: yes

    - name: Install tools
      become: true
      command: make install_tools

    - name: Install with cargo
      command: cargo install --locked {{ item }}
      environment:
        PATH: "{{ansible_env.PATH}}:{{ansible_env.HOME}}/.cargo/bin"
      loop:
        - bat
        - cargo-update
        - exa
        - killport
        - sheldon

    - name: Install rtx
      environment:
        PATH: "{{ansible_env.PATH}}:{{ansible_env.HOME}}/.cargo/bin"
      command: make setup/rtx

    - name: Install alacritty dependencies
      become: true
      apt:
        pkg:
          - cmake
          - pkg-config
          - libfreetype6-dev
          - libfontconfig1-dev
          - libxcb-xfixes0-dev
          - libxkbcommon-dev
          - python3
        state: present
        update_cache: yes

    - name: Build alacritty
      become: true
      environment:
        PATH: "{{ansible_env.PATH}}:{{ansible_env.HOME}}/.cargo/bin"
      command: make setup/alacritty

    - name: Install neovim dependencies
      become: true
      apt:
        pkg:
          - ninja-build
          - gettext
          - libtool
          - libtool-bin
          - autoconf
          - automake
          - cmake
          - g++
          - pkg-config
          - unzip
          - curl
        state: present
        update_cache: yes

    - name: Build neovim
      become: true
      command: make setup/nvim

  when: ansible_os_family == "Debian"
