- block:
  - name: homebrew update
    community.general.homebrew:
      update_homebrew: yes

  - name: homebrew tap
    community.general.homebrew_tap:
      state: present
      name:
        - github/gh
        - homebrew/bundle
        - homebrew/cask-fonts
        - homebrew/cask-versions
        - homebrew/core

  - name: install package using homebrew
    community.general.homebrew:
      state: present
      name:
        - bat
        - exa
        - fzf
        - gh
        - ghq
        - git
        - htop
        - hub
        - neofetch
        - peco
        - ripgrep
        - tig
        - tmux

  - name: install neovim head
    community.general.homebrew:
      state: latest
      name:
        - neovim

  - name: install cask package using homebrew
    community.general.homebrew_cask:
      state: present
      name:
        - alacritty
  when: ansible_os_family == "Darwin"
