- block:
    - name: Homebrew update
      community.general.homebrew:
        update_homebrew: yes

    - name: Install package using homebrew
      community.general.homebrew:
        state: present
        name:
          - bat
          - exa
          - fzf
          - gh
          - ghq
          - git
          - htop
          - hub
          - jq
          - koekeishiya/formulae/skhd
          - neofetch
          - peco
          - ripgrep
          - tig
          - tmux
          - unar
          - yabai
          - zsh

    - name: Install tools
      shell: make install_tools

    - name: Install rtx
      shell: source "$HOME/.cargo/env" && make setup/rtx
      args:
        executable: /bin/bash

    - name: Build alacritty
      become: true
      shell: make setup/alacritty

    - name: Install neovim dependencies
      community.general.homebrew:
        state: present
        name:
          - ninja
          - libtool
          - automake
          - cmake
          - pkg-config
          - gettext
          - curl

    - name: Build neovim
      become: true
      shell: make setup/nvim

  when: ansible_os_family == "Darwin"
