- block:
    - name: Homebrew update
      community.general.homebrew:
        update_homebrew: yes

    - name: Install package using homebrew
      community.general.homebrew:
        state: present
        name:
          - bat
          - exa
          - fzf
          - gh
          - ghq
          - git
          - htop
          - hub
          - jq
          - neofetch
          - peco
          - ripgrep
          - tig
          - tmux
          - zsh

    - name: Install rust
      become: true
      shell: make setup/rust

    - name: Build alacritty
      become: true
      shell: make setup/alacritty

    - name: Install neovim dependencies
      community.general.homebrew:
        state: present
        name:
          - ninja
          - libtool
          - automake
          - cmake
          - pkg-config
          - gettext
          - curl

    - name: Build neovim
      become: true
      shell: make setup/nvim

    - name: Install asdf
      shell: make setup/asdf

  when: ansible_os_family == "Darwin"
