- block:
    - name: Install package using homebrew
      command: brew install {{ item }}
      loop:
        - bat
        - exa
        - fzf
        - gh
        - ghq
        - git
        - gzip
        - htop
        - jq
        - koekeishiya/formulae/skhd
        - neofetch
        - peco
        - ripgrep
        - scdoc
        - scdoc
        - tig
        - tmux
        - yabai
        - zsh

    - name: Install tools
      command: make install_tools

    - name: Install with cargo
      command: cargo install --locked {{ item }}
      environment:
        PATH: "{{ansible_env.PATH}}:{{ansible_env.HOME}}/.cargo/env"
      loop:
        - cargo-update
        - killport
        - sheldon

    - name: Install rtx
      environment:
        PATH: "{{ansible_env.PATH}}:{{ansible_env.HOME}}/.cargo/env"
      command: make setup/rtx

    - name: Build alacritty
      become: true
      environment:
        PATH: "{{ansible_env.PATH}}:{{ansible_env.HOME}}/.cargo/env"
      command: make setup/alacritty

    - name: Install neovim dependencies
      community.general.homebrew:
        state: present
        name:

    - name: Install neovim dependencies
      command: brew install {{ item }}
      loop:
        - ninja
        - libtool
        - automake
        - cmake
        - pkg-config
        - gettext
        - curl

    - name: Build neovim
      become: true
      command: make setup/nvim

  when: ansible_os_family == "Darwin"
