- block:
    - name: Install package using homebrew
      shell: brew install {{ item }}
      loop:
        - bat
        - exa
        - fzf
        - gh
        - ghq
        - git
        - gzip
        - htop
        - jq
        - koekeishiya/formulae/skhd
        - neofetch
        - peco
        - ripgrep
        - scdoc
        - scdoc
        - tig
        - tmux
        - yabai
        - zsh

    - name: Install tools
      shell: make install_tools

    - name: Install with cargo
      shell: |
        source "$HOME/.cargo/env"
        cargo install \
          cargo-update \
          killport
      args:
        executable: /bin/bash

    - name: Install rtx
      shell: source "$HOME/.cargo/env" && make setup/rtx
      args:
        executable: /bin/bash

    - name: Build alacritty
      become: true
      shell: make setup/alacritty

    - name: Install neovim dependencies
      community.general.homebrew:
        state: present
        name:

    - name: Install neovim dependencies
      shell: brew install {{ item }}
      loop:
        - ninja
        - libtool
        - automake
        - cmake
        - pkg-config
        - gettext
        - curl

    - name: Build neovim
      become: true
      shell: make setup/nvim

  when: ansible_os_family == "Darwin"
