
[config]
  runcmd = "{{ .dir }}/main"
  buildcmd = "g++ -o {{ .dir }}/main {{ .file }} -I/home/duglaser/src/github.com/DuGlaser/atcoder-answer/ac-library/"
  filename = "main.cpp"
  lang = "4003"
  template = """
#include <atcoder/all>
#include <bits/stdc++.h>
using namespace std;
using namespace atcoder;

template <class T> using vc = vector<T>;
template <class T> using vvc = vc<vc<T>>;

using ll = long long;

#define rep(i, n) for (ll i = 0; i < n; i++)
#define per(i, n) for (ll i = n - 1; i >= 0; i--)
#define Rep(i, sta, n) for (ll i = sta; i < n; i++)
#define rep1(i, n) for (ll i = 1; i <= n; i++)
#define per1(i, n) for (ll i = n; i >= 1; i--)
#define Rep1(i, sta, n) for (ll i = sta; i <= n; i++)
#define all(v) (v).begin(), (v).end()
#define MOD 998244353;

int main() {

}
"""
