name: macos

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install ansible
        run: |
          chmod +x ./.bin/mac/install_ansible.sh
          ./.bin/mac/install_ansible.sh

      - name: setup
        run: make init
