name: ubuntu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup
        run: make init

      - name: check
        run: |
          ls -la $HOME
          source ./.zshrc
          which asdf
