name: ubuntu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create symbolic link.
        run: |
          chmod +x ./.bin/init_setup.sh
          ./.bin/init_setup.sh

      - name: Install ansible
        run: |
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible
          sudo chown -R $(whoami) ~/.ansible/tmp

      - name: Install tools
        run: ansible-playbook -i inventory/localhost install.yml
